spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            statuses: BAD_GATEWAY
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: parse-expression
          uri: lb://parser/parse
          predicates: 
          - Path=/parse/
          filters:
          - name: CircuitBreaker
            args: 
              name: parsecircuitbreaker
              slidingWindowSize: 2
              permittedNumberOfCallsInHalfOpenState: 1
              failureRateThreshold: 50
              waitDurationInOpenState: 5000